### ISSUE TITLE
Icono no se ve

### ISSUE THREAD

**Issue by Marc-Ferrer-Castillo** [Marc-Ferrer-Castillo/ABP#41]
He cargado un icono de un cohete para los formularios pero el del menú principal no se visualiza al hacer alt + tab…

![iconofalta](https://user-images.githubusercontent.com/55625687/68125200-4ba2d400-ff11-11e9-9d3c-7bd75ee4356f.png)

**Comment by albertricart** [comment]
Solucionado. La propiedad "show icon" debe estar en true, además he añadido el texto de la ventana en la que nos encontremos con la propiedad del form "text"
