### ISSUE TITLE
Gestor personajes

### ISSUE THREAD

**Issue by Marc-Ferrer-Castillo** [Marc-Ferrer-Castillo/ABP#42]
Os asigno a los dos @ivancg86 @albertricart porque lo estáis haciendo vosotros, podéis usar los comentarios de aquí para problemas o cualquier cosa relacionada de este formulario 😃 

Con tal de poder exportar todo desde el menú principal es necesario:

1. Que los **personajes se guarden en la lista estática el menú principal**
2. Necesitamos que el **menú principal reciba** las **imágenes** (podría recibir solo la dirección del fichero)

**Comment by ivancg86** [comment]
ok

**Comment by ivancg86** [comment]
En principio funciona todo bien falta revisar entre todos para ver si falta algo

**Comment by Marc-Ferrer-Castillo** [comment]
llegan las imágenes al menú principal? No he podido ver bien el código, luego lo pruebo
